## 01. Import Libraries and Data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#import data

path = r'/Users/juliewhitton/Desktop/Personal Project/'
df = pd.read_csv(os.path.join(path, 'Data', 'Intermediary Data', 'incident_characteristics.csv'), low_memory = False)
df.head()

,incident_id,0,1,2,3,4,5,6,7,8,...,27,28,29,30,31,32,33,34,35,36
0,95289,Shots Fired - No Injuries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,92401,Officer Involved Incident,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,92383,"Shot - Dead (murder, accidental, suicide)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,92142,Shot - Wounded/Injured,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,95261,Shot - Wounded/Injured,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 02. Filter Out Non-violent Incidents

In [3]:
#view values

pd.set_option("display.max_rows", None)
df['0'].value_counts(dropna = False)

Shot - Wounded/Injured                                                                                  88588
Shot - Dead (murder, accidental, suicide)                                                               42405
Non-Shooting Incident                                                                                   38550
Shots Fired - No Injuries                                                                               31599
Armed robbery with injury/death and/or evidence of DGU found                                             7528
Institution/Group/Business                                                                               3612
TSA Action                                                                                               2653
Brandishing/flourishing/open carry/lost/found                                                            1350
Home Invasion                                                                                            1321
Possession (gun(s) found during commission of other crimes)                                              1308
Drug involvement                                                                                         1001
Shots fired, no action (reported, no evidence found)                                                      955
Gun(s) stolen from owner                                                                                  833
Officer Involved Incident                                                                                 690
ATF/LE Confiscation/Raid/Arrest                                                                           448
Car-jacking                                                                                               388
NaN                                                                                                       312
Animal shot/killed                                                                                        308
Domestic Violence                                                                                         234
Accidental Shooting                                                                                       229
Gang involvement                                                                                          177
School Incident                                                                                           117
Sex crime involving firearm                                                                               103
Kidnapping/abductions/hostage                                                                              95
Implied Weapon                                                                                             88
Drive-by (car to street, car to car)                                                                       88
Pistol-whipping                                                                                            87
Suicide - Attempt                                                                                          74
Possession of gun by felon or prohibited person                                                            62
Gun buy back action                                                                                        58
Non-Aggression Incident                                                                                    50
Defensive Use                                                                                              49
Suicide^                                                                                                   32
Criminal act with stolen gun                                                                               30
Road rage                                                                                                  28
Gun at school, no death/injury - elementary/secondary school                                               25
Murder/Suicide                                                                                             24
Bar/club incident - in or around establishment                                                             23
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                                                        12
Guns stolen from law enforcement                                                                            9
Stolen/Illegally owned gun{s} recovered during arrest/warrant                                               8
BB/Pellet/Replica gun                                                                                       6
Attempted Murder/Suicide (one variable unsuccessful)                                                        6
Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )                  6
Gun shop robbery or burglary                                                                                5
ShotSpotter                                                                                                 5
Hate crime                                                                                                  4
Spree Shooting (multiple victims, multiple locations)                                                       4
Child Involved Incident                                                                                     4
House party                                                                                                 3
Gun range/gun shop/gun show shooting                                                                        1
Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)        1
Unlawful purchase/sale                                                                                      1
Name: 0, dtype: int64

In [6]:
#Create new df for non-violent incs

partial_strings = ['TSA', 'ATF', 'Gun buy back']

# Define the range of columns
start_column = '0'
end_column = '18'

# Convert columns to string type
column_range = df.loc[:, start_column:end_column].astype(str)

# Check if partial string is present in the range of columns
condition = column_range.apply(lambda x: x.str.contains('|'.join(partial_strings), na=False))

# Check if any of the partial strings are present in any column
condition = condition.any(axis=1)

# Filter the DataFrame based on the condition
filtered_df = df[condition]

index_list = filtered_df.index.tolist()

df_buyback = df.loc[index_list]

df_buyback.head()

,incident_id,0,1,2,3,4,5,6,7,8,...,27,28,29,30,31,32,33,34,35,36
34,854799,Non-Shooting Incident,NaN,Drug involvement,NaN,ATF/LE Confiscation/Raid/Arrest,NaN,Possession (gun(s) found during commission of ...,NaN,Unlawful purchase/sale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,217091,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,261045,Non-Shooting Incident,NaN,Under the influence of alcohol or drugs (only ...,NaN,ATF/LE Confiscation/Raid/Arrest,NaN,Possession (gun(s) found during commission of ...,NaN,Possession of gun by felon or prohibited person,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,217092,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,217093,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_buyback.shape

(21229, 38)

In [8]:
df_buyback['0'].value_counts(dropna = False)

Non-Shooting Incident                                                                         14496
TSA Action                                                                                     2653
Shots Fired - No Injuries                                                                      1153
Shot - Wounded/Injured                                                                          849
Institution/Group/Business                                                                      827
ATF/LE Confiscation/Raid/Arrest                                                                 448
Shot - Dead (murder, accidental, suicide)                                                       382
Drug involvement                                                                                284
Gun buy back action                                                                              58
Gang involvement                                                                                 38
Officer Involved Incident                                                                        13
Non-Aggression Incident                                                                           7
Suicide - Attempt                                                                                 4
Armed robbery with injury/death and/or evidence of DGU found                                      3
Car-jacking                                                                                       2
Domestic Violence                                                                                 2
Accidental Shooting                                                                               2
Home Invasion                                                                                     2
Stolen/Illegally owned gun{s} recovered during arrest/warrant                                     1
Sex crime involving firearm                                                                       1
Shots fired, no action (reported, no evidence found)                                              1
BB/Pellet/Replica gun                                                                             1
Kidnapping/abductions/hostage                                                                     1
Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )        1
Name: 0, dtype: int64

In [13]:
#remove violent incidents from df_buyback

partial_strings = ['Accidental', 'Sex crime', 'Kidnapping', 'Domestic Violence', 'Car-jacking', 'Home Invasion',
                  'Shot -', 'Shots Fired', 'Officer Involved Incident', 'Suicide - Attempt',
                  'Armed robbery with injury/death and/or', 'rage', 'school', 'Criminal act', 'Spree', 'Child',
                  'Defensive', 'Hate', 'Workplace', 'Drive-by', 'School', 'gun show shooting', 'Pistol-whipping']

# Define the range of columns
start_column = '0'
end_column = '18'

# Convert columns to string type
column_range = df_buyback.loc[:, start_column:end_column].astype(str)

# Check if partial string is present in the range of columns
condition = column_range.apply(lambda x: x.astype(str).str.contains('|'.join(partial_strings), na=False))

# Check if any of the partial strings are present in any column
condition = condition.any(axis=1)

# Filter the DataFrame based on the condition
filtered_df = df_buyback[condition]

index_list = filtered_df.index.tolist()

df_buyback = df_buyback.drop(index_list)
df_buyback.head()

,incident_id,0,1,2,3,4,5,6,7,8,...,27,28,29,30,31,32,33,34,35,36
34,854799,Non-Shooting Incident,NaN,Drug involvement,NaN,ATF/LE Confiscation/Raid/Arrest,NaN,Possession (gun(s) found during commission of ...,NaN,Unlawful purchase/sale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,217091,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,261045,Non-Shooting Incident,NaN,Under the influence of alcohol or drugs (only ...,NaN,ATF/LE Confiscation/Raid/Arrest,NaN,Possession (gun(s) found during commission of ...,NaN,Possession of gun by felon or prohibited person,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,217092,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,217093,TSA Action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_buyback.shape

(16562, 38)

In [15]:
#check for more violent incs

df_buyback['0'].value_counts(dropna = False)

Non-Shooting Incident                                                                         12821
TSA Action                                                                                     2653
ATF/LE Confiscation/Raid/Arrest                                                                 433
Institution/Group/Business                                                                      291
Drug involvement                                                                                266
Gun buy back action                                                                              58
Gang involvement                                                                                 29
Non-Aggression Incident                                                                           7
Shots fired, no action (reported, no evidence found)                                              1
Stolen/Illegally owned gun{s} recovered during arrest/warrant                                     1
BB/Pellet/Replica gun                                                                             1
Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )        1
Name: 0, dtype: int64

In [16]:
df.shape

(225597, 38)

In [17]:
#drop non-violent incs from full df to create violent_incs

df_violent_incs = df.drop(df_buyback.index)

In [18]:
df_violent_incs.shape

(209035, 38)

In [19]:
#drop NaN cols from df_buyback

df_buyback = df_buyback.dropna(axis = 1, how = 'all')

In [20]:
df_buyback.shape

(16562, 13)

## 03.  Export DFs

In [21]:
df_buyback.to_csv(os.path.join(path, 'Data', 'Final Data', 'nv_incs.csv'), index = False)

In [22]:
df_violent_incs.to_csv(os.path.join(path, 'Data', 'Final Data', 'v_incs.csv'), index = False)